// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MenusColumns holds the columns for the "menus" table.
	MenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "title", Type: field.TypeString, Size: 100},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "path", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "component", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"menu", "button", "link"}, Default: "menu"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "hidden", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "permission", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "external_link", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "keep_alive", Type: field.TypeBool, Default: false},
		{Name: "hide_breadcrumb", Type: field.TypeBool, Default: false},
		{Name: "always_show", Type: field.TypeBool, Default: false},
		{Name: "parent_id", Type: field.TypeString, Nullable: true, Size: 26},
	}
	// MenusTable holds the schema information for the "menus" table.
	MenusTable = &schema.Table{
		Name:       "menus",
		Columns:    MenusColumns,
		PrimaryKey: []*schema.Column{MenusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "menus_menus_parent",
				Columns:    []*schema.Column{MenusColumns[19]},
				RefColumns: []*schema.Column{MenusColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "menu_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[3]},
			},
			{
				Name:    "menu_created_at",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[1]},
			},
			{
				Name:    "menu_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[2]},
			},
			{
				Name:    "menu_parent_id",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[19]},
			},
			{
				Name:    "menu_status",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[10]},
			},
			{
				Name:    "menu_type",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[9]},
			},
			{
				Name:    "menu_sort_order",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[12]},
			},
			{
				Name:    "menu_parent_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[19], MenusColumns[12]},
			},
			{
				Name:    "menu_status_sort_order",
				Unique:  false,
				Columns: []*schema.Column{MenusColumns[10], MenusColumns[12]},
			},
			{
				Name:    "menu_name_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{MenusColumns[4], MenusColumns[3]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "code", Type: field.TypeString, Size: 100},
		{Name: "resource", Type: field.TypeString, Size: 50},
		{Name: "action", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[3]},
			},
			{
				Name:    "permission_created_at",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[1]},
			},
			{
				Name:    "permission_updated_at",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[2]},
			},
			{
				Name:    "permission_code_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[5], PermissionsColumns[3]},
			},
			{
				Name:    "permission_resource_action_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[6], PermissionsColumns[7], PermissionsColumns[3]},
			},
			{
				Name:    "permission_resource",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[6]},
			},
			{
				Name:    "permission_action",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[7]},
			},
			{
				Name:    "permission_status",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[9]},
			},
			{
				Name:    "permission_is_system",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[10]},
			},
			{
				Name:    "permission_sort_order",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[11]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "code", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[3]},
			},
			{
				Name:    "role_created_at",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[1]},
			},
			{
				Name:    "role_updated_at",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[2]},
			},
			{
				Name:    "role_code_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[5], RolesColumns[3]},
			},
			{
				Name:    "role_name_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[4], RolesColumns[3]},
			},
			{
				Name:    "role_status",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[7]},
			},
			{
				Name:    "role_is_system",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[8]},
			},
			{
				Name:    "role_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[9]},
			},
		},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "completed", Type: field.TypeBool, Default: false},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high", "urgent"}, Default: "medium"},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "todo_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[3]},
			},
			{
				Name:    "todo_created_at",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[1]},
			},
			{
				Name:    "todo_updated_at",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[2]},
			},
			{
				Name:    "todo_title",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[4]},
			},
			{
				Name:    "todo_completed",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[6]},
			},
			{
				Name:    "todo_priority",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[7]},
			},
			{
				Name:    "todo_due_date",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[8]},
			},
			{
				Name:    "todo_completed_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[6], TodosColumns[3]},
			},
			{
				Name:    "todo_priority_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TodosColumns[7], TodosColumns[3]},
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "token", Type: field.TypeString, Size: 1000},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"access", "refresh"}},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_revoked", Type: field.TypeBool, Default: false},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString, Size: 26},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_users_tokens",
				Columns:    []*schema.Column{TokensColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "token_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[3]},
			},
			{
				Name:    "token_created_at",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[1]},
			},
			{
				Name:    "token_updated_at",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[2]},
			},
			{
				Name:    "token_token_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{TokensColumns[4], TokensColumns[3]},
			},
			{
				Name:    "token_user_id",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[9]},
			},
			{
				Name:    "token_user_id_type",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[9], TokensColumns[5]},
			},
			{
				Name:    "token_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[6]},
			},
			{
				Name:    "token_is_revoked",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[7]},
			},
			{
				Name:    "token_type",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[5]},
			},
			{
				Name:    "token_user_id_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[9], TokensColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "username", Type: field.TypeString, Size: 50},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_updated_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_email_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5], UsersColumns[3]},
			},
			{
				Name:    "user_username_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4], UsersColumns[3]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[7]},
			},
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[5]},
			},
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 26},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "expired"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "user_id", Type: field.TypeString, Size: 26},
		{Name: "role_id", Type: field.TypeString, Size: 26},
		{Name: "granted_by", Type: field.TypeString, Nullable: true, Size: 26},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_users_user",
				Columns:    []*schema.Column{UserRolesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_roles_role",
				Columns:    []*schema.Column{UserRolesColumns[9]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_users_granter",
				Columns:    []*schema.Column{UserRolesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userrole_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[3]},
			},
			{
				Name:    "userrole_created_at",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[1]},
			},
			{
				Name:    "userrole_updated_at",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[2]},
			},
			{
				Name:    "userrole_user_id_role_id_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[8], UserRolesColumns[9], UserRolesColumns[3]},
			},
			{
				Name:    "userrole_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[8]},
			},
			{
				Name:    "userrole_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[9]},
			},
			{
				Name:    "userrole_granted_by",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[10]},
			},
			{
				Name:    "userrole_status",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[6]},
			},
			{
				Name:    "userrole_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[5]},
			},
			{
				Name:    "userrole_granted_at",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[4]},
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeString, Size: 26},
		{Name: "permission_id", Type: field.TypeString, Size: 26},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RoleUsersColumns holds the columns for the "role_users" table.
	RoleUsersColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeString, Size: 26},
		{Name: "user_id", Type: field.TypeString, Size: 26},
	}
	// RoleUsersTable holds the schema information for the "role_users" table.
	RoleUsersTable = &schema.Table{
		Name:       "role_users",
		Columns:    RoleUsersColumns,
		PrimaryKey: []*schema.Column{RoleUsersColumns[0], RoleUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_users_role_id",
				Columns:    []*schema.Column{RoleUsersColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_users_user_id",
				Columns:    []*schema.Column{RoleUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RoleMenusColumns holds the columns for the "role_menus" table.
	RoleMenusColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeString, Size: 26},
		{Name: "menu_id", Type: field.TypeString, Size: 26},
	}
	// RoleMenusTable holds the schema information for the "role_menus" table.
	RoleMenusTable = &schema.Table{
		Name:       "role_menus",
		Columns:    RoleMenusColumns,
		PrimaryKey: []*schema.Column{RoleMenusColumns[0], RoleMenusColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_menus_role_id",
				Columns:    []*schema.Column{RoleMenusColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_menus_menu_id",
				Columns:    []*schema.Column{RoleMenusColumns[1]},
				RefColumns: []*schema.Column{MenusColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MenusTable,
		PermissionsTable,
		RolesTable,
		TodosTable,
		TokensTable,
		UsersTable,
		UserRolesTable,
		RolePermissionsTable,
		RoleUsersTable,
		RoleMenusTable,
	}
)

func init() {
	MenusTable.ForeignKeys[0].RefTable = MenusTable
	TokensTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
	UserRolesTable.ForeignKeys[2].RefTable = UsersTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	RoleUsersTable.ForeignKeys[0].RefTable = RolesTable
	RoleUsersTable.ForeignKeys[1].RefTable = UsersTable
	RoleMenusTable.ForeignKeys[0].RefTable = RolesTable
	RoleMenusTable.ForeignKeys[1].RefTable = MenusTable
}
