// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liukeshao/echo-template/ent/department"
	"github.com/liukeshao/echo-template/ent/predicate"
	"github.com/liukeshao/echo-template/ent/user"
)

// DepartmentUpdate is the builder for updating Department entities.
type DepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentMutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (du *DepartmentUpdate) Where(ps ...predicate.Department) *DepartmentUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DepartmentUpdate) SetUpdatedAt(t time.Time) *DepartmentUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetDeletedAt sets the "deleted_at" field.
func (du *DepartmentUpdate) SetDeletedAt(i int64) *DepartmentUpdate {
	du.mutation.ResetDeletedAt()
	du.mutation.SetDeletedAt(i)
	return du
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableDeletedAt(i *int64) *DepartmentUpdate {
	if i != nil {
		du.SetDeletedAt(*i)
	}
	return du
}

// AddDeletedAt adds i to the "deleted_at" field.
func (du *DepartmentUpdate) AddDeletedAt(i int64) *DepartmentUpdate {
	du.mutation.AddDeletedAt(i)
	return du
}

// SetParentID sets the "parent_id" field.
func (du *DepartmentUpdate) SetParentID(s string) *DepartmentUpdate {
	du.mutation.SetParentID(s)
	return du
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableParentID(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetParentID(*s)
	}
	return du
}

// ClearParentID clears the value of the "parent_id" field.
func (du *DepartmentUpdate) ClearParentID() *DepartmentUpdate {
	du.mutation.ClearParentID()
	return du
}

// SetName sets the "name" field.
func (du *DepartmentUpdate) SetName(s string) *DepartmentUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableName(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetCode sets the "code" field.
func (du *DepartmentUpdate) SetCode(s string) *DepartmentUpdate {
	du.mutation.SetCode(s)
	return du
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableCode(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetCode(*s)
	}
	return du
}

// SetManager sets the "manager" field.
func (du *DepartmentUpdate) SetManager(s string) *DepartmentUpdate {
	du.mutation.SetManager(s)
	return du
}

// SetNillableManager sets the "manager" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableManager(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetManager(*s)
	}
	return du
}

// ClearManager clears the value of the "manager" field.
func (du *DepartmentUpdate) ClearManager() *DepartmentUpdate {
	du.mutation.ClearManager()
	return du
}

// SetManagerID sets the "manager_id" field.
func (du *DepartmentUpdate) SetManagerID(s string) *DepartmentUpdate {
	du.mutation.SetManagerID(s)
	return du
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableManagerID(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetManagerID(*s)
	}
	return du
}

// ClearManagerID clears the value of the "manager_id" field.
func (du *DepartmentUpdate) ClearManagerID() *DepartmentUpdate {
	du.mutation.ClearManagerID()
	return du
}

// SetPhone sets the "phone" field.
func (du *DepartmentUpdate) SetPhone(s string) *DepartmentUpdate {
	du.mutation.SetPhone(s)
	return du
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillablePhone(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetPhone(*s)
	}
	return du
}

// ClearPhone clears the value of the "phone" field.
func (du *DepartmentUpdate) ClearPhone() *DepartmentUpdate {
	du.mutation.ClearPhone()
	return du
}

// SetDescription sets the "description" field.
func (du *DepartmentUpdate) SetDescription(s string) *DepartmentUpdate {
	du.mutation.SetDescription(s)
	return du
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableDescription(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetDescription(*s)
	}
	return du
}

// ClearDescription clears the value of the "description" field.
func (du *DepartmentUpdate) ClearDescription() *DepartmentUpdate {
	du.mutation.ClearDescription()
	return du
}

// SetSortOrder sets the "sort_order" field.
func (du *DepartmentUpdate) SetSortOrder(i int) *DepartmentUpdate {
	du.mutation.ResetSortOrder()
	du.mutation.SetSortOrder(i)
	return du
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableSortOrder(i *int) *DepartmentUpdate {
	if i != nil {
		du.SetSortOrder(*i)
	}
	return du
}

// AddSortOrder adds i to the "sort_order" field.
func (du *DepartmentUpdate) AddSortOrder(i int) *DepartmentUpdate {
	du.mutation.AddSortOrder(i)
	return du
}

// SetStatus sets the "status" field.
func (du *DepartmentUpdate) SetStatus(d department.Status) *DepartmentUpdate {
	du.mutation.SetStatus(d)
	return du
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableStatus(d *department.Status) *DepartmentUpdate {
	if d != nil {
		du.SetStatus(*d)
	}
	return du
}

// SetLevel sets the "level" field.
func (du *DepartmentUpdate) SetLevel(i int) *DepartmentUpdate {
	du.mutation.ResetLevel()
	du.mutation.SetLevel(i)
	return du
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillableLevel(i *int) *DepartmentUpdate {
	if i != nil {
		du.SetLevel(*i)
	}
	return du
}

// AddLevel adds i to the "level" field.
func (du *DepartmentUpdate) AddLevel(i int) *DepartmentUpdate {
	du.mutation.AddLevel(i)
	return du
}

// SetPath sets the "path" field.
func (du *DepartmentUpdate) SetPath(s string) *DepartmentUpdate {
	du.mutation.SetPath(s)
	return du
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (du *DepartmentUpdate) SetNillablePath(s *string) *DepartmentUpdate {
	if s != nil {
		du.SetPath(*s)
	}
	return du
}

// SetParent sets the "parent" edge to the Department entity.
func (du *DepartmentUpdate) SetParent(d *Department) *DepartmentUpdate {
	return du.SetParentID(d.ID)
}

// AddChildIDs adds the "children" edge to the Department entity by IDs.
func (du *DepartmentUpdate) AddChildIDs(ids ...string) *DepartmentUpdate {
	du.mutation.AddChildIDs(ids...)
	return du
}

// AddChildren adds the "children" edges to the Department entity.
func (du *DepartmentUpdate) AddChildren(d ...*Department) *DepartmentUpdate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (du *DepartmentUpdate) AddUserIDs(ids ...string) *DepartmentUpdate {
	du.mutation.AddUserIDs(ids...)
	return du
}

// AddUsers adds the "users" edges to the User entity.
func (du *DepartmentUpdate) AddUsers(u ...*User) *DepartmentUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.AddUserIDs(ids...)
}

// Mutation returns the DepartmentMutation object of the builder.
func (du *DepartmentUpdate) Mutation() *DepartmentMutation {
	return du.mutation
}

// ClearParent clears the "parent" edge to the Department entity.
func (du *DepartmentUpdate) ClearParent() *DepartmentUpdate {
	du.mutation.ClearParent()
	return du
}

// ClearChildren clears all "children" edges to the Department entity.
func (du *DepartmentUpdate) ClearChildren() *DepartmentUpdate {
	du.mutation.ClearChildren()
	return du
}

// RemoveChildIDs removes the "children" edge to Department entities by IDs.
func (du *DepartmentUpdate) RemoveChildIDs(ids ...string) *DepartmentUpdate {
	du.mutation.RemoveChildIDs(ids...)
	return du
}

// RemoveChildren removes "children" edges to Department entities.
func (du *DepartmentUpdate) RemoveChildren(d ...*Department) *DepartmentUpdate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (du *DepartmentUpdate) ClearUsers() *DepartmentUpdate {
	du.mutation.ClearUsers()
	return du
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (du *DepartmentUpdate) RemoveUserIDs(ids ...string) *DepartmentUpdate {
	du.mutation.RemoveUserIDs(ids...)
	return du
}

// RemoveUsers removes "users" edges to User entities.
func (du *DepartmentUpdate) RemoveUsers(u ...*User) *DepartmentUpdate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DepartmentUpdate) Save(ctx context.Context) (int, error) {
	if err := du.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DepartmentUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DepartmentUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DepartmentUpdate) defaults() error {
	if _, ok := du.mutation.UpdatedAt(); !ok {
		if department.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized department.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := department.UpdateDefaultUpdatedAt()
		du.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (du *DepartmentUpdate) check() error {
	if v, ok := du.mutation.ParentID(); ok {
		if err := department.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Department.parent_id": %w`, err)}
		}
	}
	if v, ok := du.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	if v, ok := du.mutation.Code(); ok {
		if err := department.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Department.code": %w`, err)}
		}
	}
	if v, ok := du.mutation.Manager(); ok {
		if err := department.ManagerValidator(v); err != nil {
			return &ValidationError{Name: "manager", err: fmt.Errorf(`ent: validator failed for field "Department.manager": %w`, err)}
		}
	}
	if v, ok := du.mutation.ManagerID(); ok {
		if err := department.ManagerIDValidator(v); err != nil {
			return &ValidationError{Name: "manager_id", err: fmt.Errorf(`ent: validator failed for field "Department.manager_id": %w`, err)}
		}
	}
	if v, ok := du.mutation.Phone(); ok {
		if err := department.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Department.phone": %w`, err)}
		}
	}
	if v, ok := du.mutation.Description(); ok {
		if err := department.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Department.description": %w`, err)}
		}
	}
	if v, ok := du.mutation.Status(); ok {
		if err := department.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Department.status": %w`, err)}
		}
	}
	if v, ok := du.mutation.Path(); ok {
		if err := department.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Department.path": %w`, err)}
		}
	}
	return nil
}

func (du *DepartmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeString))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := du.mutation.AddedDeletedAt(); ok {
		_spec.AddField(department.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.Code(); ok {
		_spec.SetField(department.FieldCode, field.TypeString, value)
	}
	if value, ok := du.mutation.Manager(); ok {
		_spec.SetField(department.FieldManager, field.TypeString, value)
	}
	if du.mutation.ManagerCleared() {
		_spec.ClearField(department.FieldManager, field.TypeString)
	}
	if value, ok := du.mutation.ManagerID(); ok {
		_spec.SetField(department.FieldManagerID, field.TypeString, value)
	}
	if du.mutation.ManagerIDCleared() {
		_spec.ClearField(department.FieldManagerID, field.TypeString)
	}
	if value, ok := du.mutation.Phone(); ok {
		_spec.SetField(department.FieldPhone, field.TypeString, value)
	}
	if du.mutation.PhoneCleared() {
		_spec.ClearField(department.FieldPhone, field.TypeString)
	}
	if value, ok := du.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if du.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if value, ok := du.mutation.SortOrder(); ok {
		_spec.SetField(department.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := du.mutation.AddedSortOrder(); ok {
		_spec.AddField(department.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := du.mutation.Status(); ok {
		_spec.SetField(department.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := du.mutation.Level(); ok {
		_spec.SetField(department.FieldLevel, field.TypeInt, value)
	}
	if value, ok := du.mutation.AddedLevel(); ok {
		_spec.AddField(department.FieldLevel, field.TypeInt, value)
	}
	if value, ok := du.mutation.Path(); ok {
		_spec.SetField(department.FieldPath, field.TypeString, value)
	}
	if du.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !du.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedUsersIDs(); len(nodes) > 0 && !du.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DepartmentUpdateOne is the builder for updating a single Department entity.
type DepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DepartmentUpdateOne) SetUpdatedAt(t time.Time) *DepartmentUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetDeletedAt sets the "deleted_at" field.
func (duo *DepartmentUpdateOne) SetDeletedAt(i int64) *DepartmentUpdateOne {
	duo.mutation.ResetDeletedAt()
	duo.mutation.SetDeletedAt(i)
	return duo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableDeletedAt(i *int64) *DepartmentUpdateOne {
	if i != nil {
		duo.SetDeletedAt(*i)
	}
	return duo
}

// AddDeletedAt adds i to the "deleted_at" field.
func (duo *DepartmentUpdateOne) AddDeletedAt(i int64) *DepartmentUpdateOne {
	duo.mutation.AddDeletedAt(i)
	return duo
}

// SetParentID sets the "parent_id" field.
func (duo *DepartmentUpdateOne) SetParentID(s string) *DepartmentUpdateOne {
	duo.mutation.SetParentID(s)
	return duo
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableParentID(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetParentID(*s)
	}
	return duo
}

// ClearParentID clears the value of the "parent_id" field.
func (duo *DepartmentUpdateOne) ClearParentID() *DepartmentUpdateOne {
	duo.mutation.ClearParentID()
	return duo
}

// SetName sets the "name" field.
func (duo *DepartmentUpdateOne) SetName(s string) *DepartmentUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableName(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetCode sets the "code" field.
func (duo *DepartmentUpdateOne) SetCode(s string) *DepartmentUpdateOne {
	duo.mutation.SetCode(s)
	return duo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableCode(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetCode(*s)
	}
	return duo
}

// SetManager sets the "manager" field.
func (duo *DepartmentUpdateOne) SetManager(s string) *DepartmentUpdateOne {
	duo.mutation.SetManager(s)
	return duo
}

// SetNillableManager sets the "manager" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableManager(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetManager(*s)
	}
	return duo
}

// ClearManager clears the value of the "manager" field.
func (duo *DepartmentUpdateOne) ClearManager() *DepartmentUpdateOne {
	duo.mutation.ClearManager()
	return duo
}

// SetManagerID sets the "manager_id" field.
func (duo *DepartmentUpdateOne) SetManagerID(s string) *DepartmentUpdateOne {
	duo.mutation.SetManagerID(s)
	return duo
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableManagerID(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetManagerID(*s)
	}
	return duo
}

// ClearManagerID clears the value of the "manager_id" field.
func (duo *DepartmentUpdateOne) ClearManagerID() *DepartmentUpdateOne {
	duo.mutation.ClearManagerID()
	return duo
}

// SetPhone sets the "phone" field.
func (duo *DepartmentUpdateOne) SetPhone(s string) *DepartmentUpdateOne {
	duo.mutation.SetPhone(s)
	return duo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillablePhone(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetPhone(*s)
	}
	return duo
}

// ClearPhone clears the value of the "phone" field.
func (duo *DepartmentUpdateOne) ClearPhone() *DepartmentUpdateOne {
	duo.mutation.ClearPhone()
	return duo
}

// SetDescription sets the "description" field.
func (duo *DepartmentUpdateOne) SetDescription(s string) *DepartmentUpdateOne {
	duo.mutation.SetDescription(s)
	return duo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableDescription(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetDescription(*s)
	}
	return duo
}

// ClearDescription clears the value of the "description" field.
func (duo *DepartmentUpdateOne) ClearDescription() *DepartmentUpdateOne {
	duo.mutation.ClearDescription()
	return duo
}

// SetSortOrder sets the "sort_order" field.
func (duo *DepartmentUpdateOne) SetSortOrder(i int) *DepartmentUpdateOne {
	duo.mutation.ResetSortOrder()
	duo.mutation.SetSortOrder(i)
	return duo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableSortOrder(i *int) *DepartmentUpdateOne {
	if i != nil {
		duo.SetSortOrder(*i)
	}
	return duo
}

// AddSortOrder adds i to the "sort_order" field.
func (duo *DepartmentUpdateOne) AddSortOrder(i int) *DepartmentUpdateOne {
	duo.mutation.AddSortOrder(i)
	return duo
}

// SetStatus sets the "status" field.
func (duo *DepartmentUpdateOne) SetStatus(d department.Status) *DepartmentUpdateOne {
	duo.mutation.SetStatus(d)
	return duo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableStatus(d *department.Status) *DepartmentUpdateOne {
	if d != nil {
		duo.SetStatus(*d)
	}
	return duo
}

// SetLevel sets the "level" field.
func (duo *DepartmentUpdateOne) SetLevel(i int) *DepartmentUpdateOne {
	duo.mutation.ResetLevel()
	duo.mutation.SetLevel(i)
	return duo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillableLevel(i *int) *DepartmentUpdateOne {
	if i != nil {
		duo.SetLevel(*i)
	}
	return duo
}

// AddLevel adds i to the "level" field.
func (duo *DepartmentUpdateOne) AddLevel(i int) *DepartmentUpdateOne {
	duo.mutation.AddLevel(i)
	return duo
}

// SetPath sets the "path" field.
func (duo *DepartmentUpdateOne) SetPath(s string) *DepartmentUpdateOne {
	duo.mutation.SetPath(s)
	return duo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (duo *DepartmentUpdateOne) SetNillablePath(s *string) *DepartmentUpdateOne {
	if s != nil {
		duo.SetPath(*s)
	}
	return duo
}

// SetParent sets the "parent" edge to the Department entity.
func (duo *DepartmentUpdateOne) SetParent(d *Department) *DepartmentUpdateOne {
	return duo.SetParentID(d.ID)
}

// AddChildIDs adds the "children" edge to the Department entity by IDs.
func (duo *DepartmentUpdateOne) AddChildIDs(ids ...string) *DepartmentUpdateOne {
	duo.mutation.AddChildIDs(ids...)
	return duo
}

// AddChildren adds the "children" edges to the Department entity.
func (duo *DepartmentUpdateOne) AddChildren(d ...*Department) *DepartmentUpdateOne {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (duo *DepartmentUpdateOne) AddUserIDs(ids ...string) *DepartmentUpdateOne {
	duo.mutation.AddUserIDs(ids...)
	return duo
}

// AddUsers adds the "users" edges to the User entity.
func (duo *DepartmentUpdateOne) AddUsers(u ...*User) *DepartmentUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.AddUserIDs(ids...)
}

// Mutation returns the DepartmentMutation object of the builder.
func (duo *DepartmentUpdateOne) Mutation() *DepartmentMutation {
	return duo.mutation
}

// ClearParent clears the "parent" edge to the Department entity.
func (duo *DepartmentUpdateOne) ClearParent() *DepartmentUpdateOne {
	duo.mutation.ClearParent()
	return duo
}

// ClearChildren clears all "children" edges to the Department entity.
func (duo *DepartmentUpdateOne) ClearChildren() *DepartmentUpdateOne {
	duo.mutation.ClearChildren()
	return duo
}

// RemoveChildIDs removes the "children" edge to Department entities by IDs.
func (duo *DepartmentUpdateOne) RemoveChildIDs(ids ...string) *DepartmentUpdateOne {
	duo.mutation.RemoveChildIDs(ids...)
	return duo
}

// RemoveChildren removes "children" edges to Department entities.
func (duo *DepartmentUpdateOne) RemoveChildren(d ...*Department) *DepartmentUpdateOne {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (duo *DepartmentUpdateOne) ClearUsers() *DepartmentUpdateOne {
	duo.mutation.ClearUsers()
	return duo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (duo *DepartmentUpdateOne) RemoveUserIDs(ids ...string) *DepartmentUpdateOne {
	duo.mutation.RemoveUserIDs(ids...)
	return duo
}

// RemoveUsers removes "users" edges to User entities.
func (duo *DepartmentUpdateOne) RemoveUsers(u ...*User) *DepartmentUpdateOne {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (duo *DepartmentUpdateOne) Where(ps ...predicate.Department) *DepartmentUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DepartmentUpdateOne) Select(field string, fields ...string) *DepartmentUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Department entity.
func (duo *DepartmentUpdateOne) Save(ctx context.Context) (*Department, error) {
	if err := duo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DepartmentUpdateOne) SaveX(ctx context.Context) *Department {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DepartmentUpdateOne) defaults() error {
	if _, ok := duo.mutation.UpdatedAt(); !ok {
		if department.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized department.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := department.UpdateDefaultUpdatedAt()
		duo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (duo *DepartmentUpdateOne) check() error {
	if v, ok := duo.mutation.ParentID(); ok {
		if err := department.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Department.parent_id": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Code(); ok {
		if err := department.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Department.code": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Manager(); ok {
		if err := department.ManagerValidator(v); err != nil {
			return &ValidationError{Name: "manager", err: fmt.Errorf(`ent: validator failed for field "Department.manager": %w`, err)}
		}
	}
	if v, ok := duo.mutation.ManagerID(); ok {
		if err := department.ManagerIDValidator(v); err != nil {
			return &ValidationError{Name: "manager_id", err: fmt.Errorf(`ent: validator failed for field "Department.manager_id": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Phone(); ok {
		if err := department.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Department.phone": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Description(); ok {
		if err := department.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Department.description": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Status(); ok {
		if err := department.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Department.status": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Path(); ok {
		if err := department.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Department.path": %w`, err)}
		}
	}
	return nil
}

func (duo *DepartmentUpdateOne) sqlSave(ctx context.Context) (_node *Department, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeString))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Department.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, department.FieldID)
		for _, f := range fields {
			if !department.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != department.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.AddedDeletedAt(); ok {
		_spec.AddField(department.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.Code(); ok {
		_spec.SetField(department.FieldCode, field.TypeString, value)
	}
	if value, ok := duo.mutation.Manager(); ok {
		_spec.SetField(department.FieldManager, field.TypeString, value)
	}
	if duo.mutation.ManagerCleared() {
		_spec.ClearField(department.FieldManager, field.TypeString)
	}
	if value, ok := duo.mutation.ManagerID(); ok {
		_spec.SetField(department.FieldManagerID, field.TypeString, value)
	}
	if duo.mutation.ManagerIDCleared() {
		_spec.ClearField(department.FieldManagerID, field.TypeString)
	}
	if value, ok := duo.mutation.Phone(); ok {
		_spec.SetField(department.FieldPhone, field.TypeString, value)
	}
	if duo.mutation.PhoneCleared() {
		_spec.ClearField(department.FieldPhone, field.TypeString)
	}
	if value, ok := duo.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if duo.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if value, ok := duo.mutation.SortOrder(); ok {
		_spec.SetField(department.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := duo.mutation.AddedSortOrder(); ok {
		_spec.AddField(department.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := duo.mutation.Status(); ok {
		_spec.SetField(department.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := duo.mutation.Level(); ok {
		_spec.SetField(department.FieldLevel, field.TypeInt, value)
	}
	if value, ok := duo.mutation.AddedLevel(); ok {
		_spec.AddField(department.FieldLevel, field.TypeInt, value)
	}
	if value, ok := duo.mutation.Path(); ok {
		_spec.SetField(department.FieldPath, field.TypeString, value)
	}
	if duo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   department.ParentTable,
			Columns: []string{department.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !duo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.ChildrenTable,
			Columns: []string{department.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !duo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   department.UsersTable,
			Columns: []string{department.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Department{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
