// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liukeshao/echo-template/ent/predicate"
	"github.com/liukeshao/echo-template/ent/role"
	"github.com/liukeshao/echo-template/ent/user"
	"github.com/liukeshao/echo-template/ent/userrole"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uru *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetUpdatedAt sets the "updated_at" field.
func (uru *UserRoleUpdate) SetUpdatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetDeletedAt sets the "deleted_at" field.
func (uru *UserRoleUpdate) SetDeletedAt(i int64) *UserRoleUpdate {
	uru.mutation.ResetDeletedAt()
	uru.mutation.SetDeletedAt(i)
	return uru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableDeletedAt(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetDeletedAt(*i)
	}
	return uru
}

// AddDeletedAt adds i to the "deleted_at" field.
func (uru *UserRoleUpdate) AddDeletedAt(i int64) *UserRoleUpdate {
	uru.mutation.AddDeletedAt(i)
	return uru
}

// SetUserID sets the "user_id" field.
func (uru *UserRoleUpdate) SetUserID(s string) *UserRoleUpdate {
	uru.mutation.SetUserID(s)
	return uru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableUserID(s *string) *UserRoleUpdate {
	if s != nil {
		uru.SetUserID(*s)
	}
	return uru
}

// SetRoleID sets the "role_id" field.
func (uru *UserRoleUpdate) SetRoleID(s string) *UserRoleUpdate {
	uru.mutation.SetRoleID(s)
	return uru
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableRoleID(s *string) *UserRoleUpdate {
	if s != nil {
		uru.SetRoleID(*s)
	}
	return uru
}

// SetGrantedBy sets the "granted_by" field.
func (uru *UserRoleUpdate) SetGrantedBy(s string) *UserRoleUpdate {
	uru.mutation.SetGrantedBy(s)
	return uru
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableGrantedBy(s *string) *UserRoleUpdate {
	if s != nil {
		uru.SetGrantedBy(*s)
	}
	return uru
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (uru *UserRoleUpdate) ClearGrantedBy() *UserRoleUpdate {
	uru.mutation.ClearGrantedBy()
	return uru
}

// SetGrantedAt sets the "granted_at" field.
func (uru *UserRoleUpdate) SetGrantedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetGrantedAt(t)
	return uru
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableGrantedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetGrantedAt(*t)
	}
	return uru
}

// SetExpiresAt sets the "expires_at" field.
func (uru *UserRoleUpdate) SetExpiresAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetExpiresAt(t)
	return uru
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableExpiresAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetExpiresAt(*t)
	}
	return uru
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (uru *UserRoleUpdate) ClearExpiresAt() *UserRoleUpdate {
	uru.mutation.ClearExpiresAt()
	return uru
}

// SetStatus sets the "status" field.
func (uru *UserRoleUpdate) SetStatus(u userrole.Status) *UserRoleUpdate {
	uru.mutation.SetStatus(u)
	return uru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableStatus(u *userrole.Status) *UserRoleUpdate {
	if u != nil {
		uru.SetStatus(*u)
	}
	return uru
}

// SetRemark sets the "remark" field.
func (uru *UserRoleUpdate) SetRemark(s string) *UserRoleUpdate {
	uru.mutation.SetRemark(s)
	return uru
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableRemark(s *string) *UserRoleUpdate {
	if s != nil {
		uru.SetRemark(*s)
	}
	return uru
}

// ClearRemark clears the value of the "remark" field.
func (uru *UserRoleUpdate) ClearRemark() *UserRoleUpdate {
	uru.mutation.ClearRemark()
	return uru
}

// SetUser sets the "user" edge to the User entity.
func (uru *UserRoleUpdate) SetUser(u *User) *UserRoleUpdate {
	return uru.SetUserID(u.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (uru *UserRoleUpdate) SetRole(r *Role) *UserRoleUpdate {
	return uru.SetRoleID(r.ID)
}

// SetGranterID sets the "granter" edge to the User entity by ID.
func (uru *UserRoleUpdate) SetGranterID(id string) *UserRoleUpdate {
	uru.mutation.SetGranterID(id)
	return uru
}

// SetNillableGranterID sets the "granter" edge to the User entity by ID if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableGranterID(id *string) *UserRoleUpdate {
	if id != nil {
		uru = uru.SetGranterID(*id)
	}
	return uru
}

// SetGranter sets the "granter" edge to the User entity.
func (uru *UserRoleUpdate) SetGranter(u *User) *UserRoleUpdate {
	return uru.SetGranterID(u.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uru *UserRoleUpdate) Mutation() *UserRoleMutation {
	return uru.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uru *UserRoleUpdate) ClearUser() *UserRoleUpdate {
	uru.mutation.ClearUser()
	return uru
}

// ClearRole clears the "role" edge to the Role entity.
func (uru *UserRoleUpdate) ClearRole() *UserRoleUpdate {
	uru.mutation.ClearRole()
	return uru
}

// ClearGranter clears the "granter" edge to the User entity.
func (uru *UserRoleUpdate) ClearGranter() *UserRoleUpdate {
	uru.mutation.ClearGranter()
	return uru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	if err := uru.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, uru.sqlSave, uru.mutation, uru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uru *UserRoleUpdate) defaults() error {
	if _, ok := uru.mutation.UpdatedAt(); !ok {
		if userrole.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userrole.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userrole.UpdateDefaultUpdatedAt()
		uru.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uru *UserRoleUpdate) check() error {
	if v, ok := uru.mutation.UserID(); ok {
		if err := userrole.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserRole.user_id": %w`, err)}
		}
	}
	if v, ok := uru.mutation.RoleID(); ok {
		if err := userrole.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "UserRole.role_id": %w`, err)}
		}
	}
	if v, ok := uru.mutation.GrantedBy(); ok {
		if err := userrole.GrantedByValidator(v); err != nil {
			return &ValidationError{Name: "granted_by", err: fmt.Errorf(`ent: validator failed for field "UserRole.granted_by": %w`, err)}
		}
	}
	if v, ok := uru.mutation.Status(); ok {
		if err := userrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRole.status": %w`, err)}
		}
	}
	if v, ok := uru.mutation.Remark(); ok {
		if err := userrole.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "UserRole.remark": %w`, err)}
		}
	}
	if uru.mutation.UserCleared() && len(uru.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if uru.mutation.RoleCleared() && len(uru.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (uru *UserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeString))
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uru.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedDeletedAt(); ok {
		_spec.AddField(userrole.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.GrantedAt(); ok {
		_spec.SetField(userrole.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := uru.mutation.ExpiresAt(); ok {
		_spec.SetField(userrole.FieldExpiresAt, field.TypeTime, value)
	}
	if uru.mutation.ExpiresAtCleared() {
		_spec.ClearField(userrole.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := uru.mutation.Status(); ok {
		_spec.SetField(userrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := uru.mutation.Remark(); ok {
		_spec.SetField(userrole.FieldRemark, field.TypeString, value)
	}
	if uru.mutation.RemarkCleared() {
		_spec.ClearField(userrole.FieldRemark, field.TypeString)
	}
	if uru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uru.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uru.mutation.GranterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.GranterTable,
			Columns: []string{userrole.GranterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.GranterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.GranterTable,
			Columns: []string{userrole.GranterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uru.mutation.done = true
	return n, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uruo *UserRoleUpdateOne) SetUpdatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetDeletedAt sets the "deleted_at" field.
func (uruo *UserRoleUpdateOne) SetDeletedAt(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetDeletedAt()
	uruo.mutation.SetDeletedAt(i)
	return uruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableDeletedAt(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetDeletedAt(*i)
	}
	return uruo
}

// AddDeletedAt adds i to the "deleted_at" field.
func (uruo *UserRoleUpdateOne) AddDeletedAt(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddDeletedAt(i)
	return uruo
}

// SetUserID sets the "user_id" field.
func (uruo *UserRoleUpdateOne) SetUserID(s string) *UserRoleUpdateOne {
	uruo.mutation.SetUserID(s)
	return uruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableUserID(s *string) *UserRoleUpdateOne {
	if s != nil {
		uruo.SetUserID(*s)
	}
	return uruo
}

// SetRoleID sets the "role_id" field.
func (uruo *UserRoleUpdateOne) SetRoleID(s string) *UserRoleUpdateOne {
	uruo.mutation.SetRoleID(s)
	return uruo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableRoleID(s *string) *UserRoleUpdateOne {
	if s != nil {
		uruo.SetRoleID(*s)
	}
	return uruo
}

// SetGrantedBy sets the "granted_by" field.
func (uruo *UserRoleUpdateOne) SetGrantedBy(s string) *UserRoleUpdateOne {
	uruo.mutation.SetGrantedBy(s)
	return uruo
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableGrantedBy(s *string) *UserRoleUpdateOne {
	if s != nil {
		uruo.SetGrantedBy(*s)
	}
	return uruo
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (uruo *UserRoleUpdateOne) ClearGrantedBy() *UserRoleUpdateOne {
	uruo.mutation.ClearGrantedBy()
	return uruo
}

// SetGrantedAt sets the "granted_at" field.
func (uruo *UserRoleUpdateOne) SetGrantedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetGrantedAt(t)
	return uruo
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableGrantedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetGrantedAt(*t)
	}
	return uruo
}

// SetExpiresAt sets the "expires_at" field.
func (uruo *UserRoleUpdateOne) SetExpiresAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetExpiresAt(t)
	return uruo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableExpiresAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetExpiresAt(*t)
	}
	return uruo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (uruo *UserRoleUpdateOne) ClearExpiresAt() *UserRoleUpdateOne {
	uruo.mutation.ClearExpiresAt()
	return uruo
}

// SetStatus sets the "status" field.
func (uruo *UserRoleUpdateOne) SetStatus(u userrole.Status) *UserRoleUpdateOne {
	uruo.mutation.SetStatus(u)
	return uruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableStatus(u *userrole.Status) *UserRoleUpdateOne {
	if u != nil {
		uruo.SetStatus(*u)
	}
	return uruo
}

// SetRemark sets the "remark" field.
func (uruo *UserRoleUpdateOne) SetRemark(s string) *UserRoleUpdateOne {
	uruo.mutation.SetRemark(s)
	return uruo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableRemark(s *string) *UserRoleUpdateOne {
	if s != nil {
		uruo.SetRemark(*s)
	}
	return uruo
}

// ClearRemark clears the value of the "remark" field.
func (uruo *UserRoleUpdateOne) ClearRemark() *UserRoleUpdateOne {
	uruo.mutation.ClearRemark()
	return uruo
}

// SetUser sets the "user" edge to the User entity.
func (uruo *UserRoleUpdateOne) SetUser(u *User) *UserRoleUpdateOne {
	return uruo.SetUserID(u.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (uruo *UserRoleUpdateOne) SetRole(r *Role) *UserRoleUpdateOne {
	return uruo.SetRoleID(r.ID)
}

// SetGranterID sets the "granter" edge to the User entity by ID.
func (uruo *UserRoleUpdateOne) SetGranterID(id string) *UserRoleUpdateOne {
	uruo.mutation.SetGranterID(id)
	return uruo
}

// SetNillableGranterID sets the "granter" edge to the User entity by ID if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableGranterID(id *string) *UserRoleUpdateOne {
	if id != nil {
		uruo = uruo.SetGranterID(*id)
	}
	return uruo
}

// SetGranter sets the "granter" edge to the User entity.
func (uruo *UserRoleUpdateOne) SetGranter(u *User) *UserRoleUpdateOne {
	return uruo.SetGranterID(u.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uruo *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return uruo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uruo *UserRoleUpdateOne) ClearUser() *UserRoleUpdateOne {
	uruo.mutation.ClearUser()
	return uruo
}

// ClearRole clears the "role" edge to the Role entity.
func (uruo *UserRoleUpdateOne) ClearRole() *UserRoleUpdateOne {
	uruo.mutation.ClearRole()
	return uruo
}

// ClearGranter clears the "granter" edge to the User entity.
func (uruo *UserRoleUpdateOne) ClearGranter() *UserRoleUpdateOne {
	uruo.mutation.ClearGranter()
	return uruo
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uruo *UserRoleUpdateOne) Where(ps ...predicate.UserRole) *UserRoleUpdateOne {
	uruo.mutation.Where(ps...)
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UserRoleUpdateOne) Select(field string, fields ...string) *UserRoleUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UserRole entity.
func (uruo *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	if err := uruo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, uruo.sqlSave, uruo.mutation, uruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uruo *UserRoleUpdateOne) defaults() error {
	if _, ok := uruo.mutation.UpdatedAt(); !ok {
		if userrole.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userrole.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userrole.UpdateDefaultUpdatedAt()
		uruo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uruo *UserRoleUpdateOne) check() error {
	if v, ok := uruo.mutation.UserID(); ok {
		if err := userrole.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserRole.user_id": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.RoleID(); ok {
		if err := userrole.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "UserRole.role_id": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.GrantedBy(); ok {
		if err := userrole.GrantedByValidator(v); err != nil {
			return &ValidationError{Name: "granted_by", err: fmt.Errorf(`ent: validator failed for field "UserRole.granted_by": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.Status(); ok {
		if err := userrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserRole.status": %w`, err)}
		}
	}
	if v, ok := uruo.mutation.Remark(); ok {
		if err := userrole.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "UserRole.remark": %w`, err)}
		}
	}
	if uruo.mutation.UserCleared() && len(uruo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if uruo.mutation.RoleCleared() && len(uruo.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (uruo *UserRoleUpdateOne) sqlSave(ctx context.Context) (_node *UserRole, err error) {
	if err := uruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeString))
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrole.FieldID)
		for _, f := range fields {
			if !userrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedDeletedAt(); ok {
		_spec.AddField(userrole.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.GrantedAt(); ok {
		_spec.SetField(userrole.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.ExpiresAt(); ok {
		_spec.SetField(userrole.FieldExpiresAt, field.TypeTime, value)
	}
	if uruo.mutation.ExpiresAtCleared() {
		_spec.ClearField(userrole.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := uruo.mutation.Status(); ok {
		_spec.SetField(userrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := uruo.mutation.Remark(); ok {
		_spec.SetField(userrole.FieldRemark, field.TypeString, value)
	}
	if uruo.mutation.RemarkCleared() {
		_spec.ClearField(userrole.FieldRemark, field.TypeString)
	}
	if uruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uruo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uruo.mutation.GranterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.GranterTable,
			Columns: []string{userrole.GranterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.GranterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.GranterTable,
			Columns: []string{userrole.GranterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRole{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uruo.mutation.done = true
	return _node, nil
}
