// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
